name: Rust

on:
- push
- pull_request

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    - run: sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main"
    - run: sudo apt-get update
    - run: sudo apt-get install -t llvm-toolchain-bionic-8 clang-tidy-8
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
